[package]
authors = ["Alex Whitney <adwhit@fastmail.com>"]
name = "simple-codegen"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
lazy_static = "0.2.8"
quote = "0.3.15"
rustfmt = "0.9.0"
tempdir = "0.3.5"
